// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nloefynppowbjnbmhmgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sb2VmeW5wcG93YmpuYm1obWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDE1NDgsImV4cCI6MjA2NTgxNzU0OH0.Ulc6qMlnV_3IEfrUTmijOdxXOqmq9K5-hnfrlY9R3Ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);